### ISSUE TITLE
Road network Issues

### ISSUE THREAD

**Issue by jj0hns0n** [GFDRR/afg_geonode#2]
Primary roads' is used twice in legend. Fix? Please check correct typology in layer attribute table. Can we also make the primary roads 'red'?

**Comment by jj0hns0n** [comment]
![image](https://cloud.githubusercontent.com/assets/506078/17376081/c397b91e-5968-11e6-9b0b-7fa2284b8def.png)

**Comment by maupollino** [comment]
Fixed.
