### ISSUE TITLE
Health Facilities Layer Symbology

### ISSUE THREAD

**Issue by jj0hns0n** [GFDRR/afg_geonode#5]
Health Facilities' layer: can we make the 'Provincial Hospital' and 'Regional/National Hospital' (H1 and H2) stand out better by using another symbol, e.g. a red cross and an orange cross? The others can stay the same

**Comment by jj0hns0n** [comment]
![image](https://cloud.githubusercontent.com/assets/506078/17376121/ed998436-5968-11e6-9c37-22365df3f65d.png)

**Comment by maupollino** [comment]
H1 and H2 styles modified.
